### ISSUE TITLE
can't implement JSONB "key exist" functions

### ISSUE THREAD

**Issue by valepu** [boldtrn/JsonbBundle#1] opened 2015-06-29 08:11 UTC
Hi,
I'm trying to implement the JSONB functions that check for key existance http://www.postgresql.org/docs/9.4/static/functions-json.html ( ?, |?, &? ) using your code as starting point i made this:

```
class HasElement extends FunctionNode
{
    public $leftHandSide = null;
    public $rightHandSide = null;

    public function parse(\Doctrine\ORM\Query\Parser $parser)
    {
        $parser->match(Lexer::T_IDENTIFIER);
        $parser->match(Lexer::T_OPEN_PARENTHESIS);
        $this->leftHandSide = $parser->ArithmeticPrimary();
        $parser->match(Lexer::T_COMMA);
        $this->rightHandSide = $parser->ArithmeticPrimary();
        $parser->match(Lexer::T_CLOSE_PARENTHESIS);
    }

    public function getSql(\Doctrine\ORM\Query\SqlWalker $sqlWalker)
    {
        return '(' .
        $this->leftHandSide->dispatch($sqlWalker) . " ? " .
        $this->rightHandSide->dispatch($sqlWalker) .
        ')';
    }
}
```

But it doesn't work since doctrine translates the question mark as a parameter and i get this error

```
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "$2"
LINE 1: ...id = r1_.id WHERE r0_.file_id = $1 AND (r0_.attrs $2 $3)
```

I have tried escaping, replacing with unicode sequence, passing the question mark as parameter, but none of that worked. I have asked the question on Stackoverflow too http://stackoverflow.com/questions/31055658/custom-doctrine-dql-function-with-question-mark-being-converted-into-parameter but no answer
Do you think there is a way to implement these functions or should we forward the issue to the Doctrine team?

**Comment by boldtrn** [comment] 2015-06-29 11:18
Hi @valepu 

this is no Doctrine issue, since this is the expected behavior of Doctrine.

I just committed an example and the function ;) that should work. I think the trick is to create the Query like this:

```
    public function testExistence()
    {
        $q = $this
            ->entityManager
            ->createQuery(
                "
        SELECT t
        FROM E:Test t
        WHERE JSONB_EX(t.attrs, 'value') = TRUE
        "
            );

        $expectedSQL = "SELECT t0.id AS id0, t0.attrs AS attrs1 FROM Test t0 WHERE (t0.attrs ? 'value') = true";

        $expectedSQL = str_replace("_", "", $expectedSQL);

        $actualSQL =  str_replace("_", "", $q->getSql());

        $this->assertEquals(
            $expectedSQL,
            $actualSQL
        );
    }
```

Hope this helps.

BTW: I recommend using NativeQueries, since I personally think it is more convenient, especially if you want to write more complex queries using different `json(b)` functionality. However, both should work.

Best,
Robin

**Comment by valepu** [comment] 2015-06-29 13:06
Yes sorry i never meant to say that it's an issue, it's clearly working as expected, it's just that the expected behavior conflicts with this operator (in my opinion it's a bad symbol choice on Postgres side actually)

I'll pull the new code and make some tests, thanks.

**Comment by boldtrn** [comment] 2015-06-29 13:09
Hi @valepu 

please be aware that you have to update your config.yml as well, since I added a new function.

You can use this function as shown above in my code example.
Please let me know if this solves your problem.

Best,
Robin

**Comment by valepu** [comment] 2015-06-29 16:53
Yes i am aware of that, that's how i tested the function i posted in my first message. 
By the way did you actually execute the query? While "getQuery" will give you the correct query, executing it will actually give an error.
Your JSONB_EX function is exactly the same of what i posted, which doesn't work because when executed the question mark gets translated into a parameter placeholder ($1, $2....)

I have tried a native query aswell, and still the question mark gets replaced with a parameter placeholder

**Comment by boldtrn** [comment] 2015-06-30 12:56
Hi @valepu 

Sorry I am quite busy right now, therefore I haven't checked the query. It seems this is a major problem a lot of people experiencing, since the `?` is used in several ORMs and so on.

Depending on your requirements you could use the following:

```
WHERE  (t.attrs->\'YOUR_KEY\') IS NOT NULL
```

Hope this helps.
Some links for you:
http://www.booneputney.com/2015-06-11-postgresql-jsonb-question-mark-operator-alternative/
http://stackoverflow.com/questions/19422233/check-if-field-exists-in-json-type-column-postgresql

**Comment by valepu** [comment] 2015-06-30 13:01
Thanks for your help and your time, i'll try that too. 
I think it should be the case to warn the doctrine team about this since i heard they are trying to implement jsonb natively in 2.6

**Comment by boldtrn** [comment] 2015-06-30 13:09
@valepu 

The existence and contains operator won't be supported in my opinion, since this is database specific behavior. I think they will add jsonb as datatype for json_arrays (if you have other information, please let me know).

**Comment by valepu** [comment] 2015-06-30 13:21
Ok this one works:

```
    return '(' .
    $this->leftHandSide->dispatch($sqlWalker) . " -> " .
    $this->rightHandSide->dispatch($sqlWalker) .
    ') IS NOT NULL';
```

I think you are more informed than me on this :) Should i read something else on the topic i'll let you know. Thanks a lot for the help and the library (jsonb is amazing and being able to use it with doctrine is very useful for my project)

**Comment by boldtrn** [comment] 2015-06-30 13:43
@valepu 

Happy to help. Please feel free to create a PR including Unit Tests.

**Comment by valepu** [comment] 2015-06-30 13:55
I'll do a Pull Request as soon as i can

**Comment by boldtrn** [comment] 2015-06-30 18:26
@valepu since I touched the code, due to another PR I modified the existence function. However, if you find any improvements, please let me know (and write a PR).

**Closed as completed by boldtrn** 2015-06-30 18:26 UTC
